name: hello-world-workflow
run-name: ${{ github.actor }} is starting github actions

on: 
    push

jobs:
    my_first_job:    
        runs-on: ubuntu-latest
        name: test
        steps:
            - run: echo "Hello everyone"
